# Generated by Django 5.2.8 on 2025-11-10 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='price_per_day',
            new_name='price_per_month',
        ),
    ]
