# Generated by Django 5.2.8 on 2025-11-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_car_description_remove_car_monthly_rent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='currency',
        ),
        migrations.AddField(
            model_name='car',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='cars/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='rent_per_month',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
